/*
 * This file is generated by jOOQ.
 */
package io.bricksets.rdbms;


import io.bricksets.rdbms.tables.Events;
import io.bricksets.rdbms.tables.FlywaySchemaHistory;
import io.bricksets.rdbms.tables.Tags;
import io.bricksets.rdbms.tables.records.EventsRecord;
import io.bricksets.rdbms.tables.records.FlywaySchemaHistoryRecord;
import io.bricksets.rdbms.tables.records.TagsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * sandbox.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EventsRecord> PK_EVENT = Internal.createUniqueKey(Events.EVENTS, DSL.name("pk_event"), new TableField[] { Events.EVENTS.ID }, true);
    public static final UniqueKey<EventsRecord> UC_POSITION = Internal.createUniqueKey(Events.EVENTS, DSL.name("uc_position"), new TableField[] { Events.EVENTS.POSITION }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<TagsRecord> PK_TAG = Internal.createUniqueKey(Tags.TAGS, DSL.name("pk_tag"), new TableField[] { Tags.TAGS.EVENT_ID, Tags.TAGS.TAG_CLASS, Tags.TAGS.TAG_VALUE }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TagsRecord, EventsRecord> TAGS__FK_TAG_EVENT = Internal.createForeignKey(Tags.TAGS, DSL.name("fk_tag_event"), new TableField[] { Tags.TAGS.EVENT_ID }, Keys.PK_EVENT, new TableField[] { Events.EVENTS.ID }, true);
}
