/*
 * This file is generated by jOOQ.
 */
package io.bricksets.rdbms;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in sandbox.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>sandbox.events_position_seq</code>
     */
    public static final Sequence<Long> EVENTS_POSITION_SEQ = Internal.createSequence("events_position_seq", Sandbox.SANDBOX, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
