/*
 * This file is generated by jOOQ.
 */
package io.bricksets.rdbms;


import io.bricksets.rdbms.tables.Brickset;
import io.bricksets.rdbms.tables.Event;
import io.bricksets.rdbms.tables.FlywaySchemaHistory;
import io.bricksets.rdbms.tables.Tag;


/**
 * Convenience access to all tables in sandbox.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sandbox.brickset</code>.
     */
    public static final Brickset BRICKSET = Brickset.BRICKSET;

    /**
     * The table <code>sandbox.event</code>.
     */
    public static final Event EVENT = Event.EVENT;

    /**
     * The table <code>sandbox.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>sandbox.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;
}
