/*
 * This file is generated by jOOQ.
 */
package io.bricksets.rdbms;


import io.bricksets.rdbms.tables.Events;
import io.bricksets.rdbms.tables.FlywaySchemaHistory;
import io.bricksets.rdbms.tables.Tags;


/**
 * Convenience access to all tables in sandbox.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sandbox.events</code>.
     */
    public static final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>sandbox.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>sandbox.tags</code>.
     */
    public static final Tags TAGS = Tags.TAGS;
}
