/*
 * This file is generated by jOOQ.
 */
package be.koder.bricksets.rdbms;


import be.koder.bricksets.rdbms.tables.BricksetView;
import be.koder.bricksets.rdbms.tables.Event;
import be.koder.bricksets.rdbms.tables.FlywaySchemaHistory;
import be.koder.bricksets.rdbms.tables.Tag;


/**
 * Convenience access to all tables in sandbox.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sandbox.brickset_view</code>.
     */
    public static final BricksetView BRICKSET_VIEW = BricksetView.BRICKSET_VIEW;

    /**
     * The table <code>sandbox.event</code>.
     */
    public static final Event EVENT = Event.EVENT;

    /**
     * The table <code>sandbox.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>sandbox.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;
}
