/*
 * This file is generated by jOOQ.
 */
package io.bricksets.rdbms.tables.records;


import io.bricksets.rdbms.tables.Event;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventRecord extends UpdatableRecordImpl<EventRecord> implements Record5<UUID, Long, LocalDateTime, String, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sandbox.event.id</code>.
     */
    public EventRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sandbox.event.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>sandbox.event.position</code>.
     */
    public EventRecord setPosition(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sandbox.event.position</code>.
     */
    public Long getPosition() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>sandbox.event.occurred_at</code>.
     */
    public EventRecord setOccurredAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sandbox.event.occurred_at</code>.
     */
    public LocalDateTime getOccurredAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sandbox.event.event_class</code>.
     */
    public EventRecord setEventClass(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sandbox.event.event_class</code>.
     */
    public String getEventClass() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sandbox.event.event_value</code>.
     */
    public EventRecord setEventValue(JSONB value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sandbox.event.event_value</code>.
     */
    public JSONB getEventValue() {
        return (JSONB) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, Long, LocalDateTime, String, JSONB> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, Long, LocalDateTime, String, JSONB> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Event.EVENT.ID;
    }

    @Override
    public Field<Long> field2() {
        return Event.EVENT.POSITION;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Event.EVENT.OCCURRED_AT;
    }

    @Override
    public Field<String> field4() {
        return Event.EVENT.EVENT_CLASS;
    }

    @Override
    public Field<JSONB> field5() {
        return Event.EVENT.EVENT_VALUE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getPosition();
    }

    @Override
    public LocalDateTime component3() {
        return getOccurredAt();
    }

    @Override
    public String component4() {
        return getEventClass();
    }

    @Override
    public JSONB component5() {
        return getEventValue();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getPosition();
    }

    @Override
    public LocalDateTime value3() {
        return getOccurredAt();
    }

    @Override
    public String value4() {
        return getEventClass();
    }

    @Override
    public JSONB value5() {
        return getEventValue();
    }

    @Override
    public EventRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public EventRecord value2(Long value) {
        setPosition(value);
        return this;
    }

    @Override
    public EventRecord value3(LocalDateTime value) {
        setOccurredAt(value);
        return this;
    }

    @Override
    public EventRecord value4(String value) {
        setEventClass(value);
        return this;
    }

    @Override
    public EventRecord value5(JSONB value) {
        setEventValue(value);
        return this;
    }

    @Override
    public EventRecord values(UUID value1, Long value2, LocalDateTime value3, String value4, JSONB value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventRecord
     */
    public EventRecord() {
        super(Event.EVENT);
    }

    /**
     * Create a detached, initialised EventRecord
     */
    public EventRecord(UUID id, Long position, LocalDateTime occurredAt, String eventClass, JSONB eventValue) {
        super(Event.EVENT);

        setId(id);
        setPosition(position);
        setOccurredAt(occurredAt);
        setEventClass(eventClass);
        setEventValue(eventValue);
    }
}
