io.bricksets:
  rdbms:
    enabled: false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6000/sandbox
    username: sandbox
    password: sandbox

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG