io.bricksets:
  rdbms:
    enabled: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6000/sandbox
    username: sandbox
    password: sandbox

spring:
  jpa:
    show-sql: true